### PR TITLE
[B-690] Show all repositories in project details page

### PR DESCRIPTION
**Pull request by AnthonyBuisset**
closes B-690
closes B-689

### CODE REVIEW

**Comment by oscarwroche** [comment]
There seems to be a display problem when the description is not long enough 
Screenshot 2023-02-27 at 18 57 36

**Comment by oscarwroche** [comment]
There seems to be a case when the contributor name display does not work ("github.com/undefined") @AnthonyBuisset 
Screenshot 2023-02-27 at 19 00 25

**Review by oscarwroche — CHANGES_REQUESTED** [review]
See visual edges cases in this thread / in Chromatic

**Comment by AnthonyBuisset** [comment]
> There seems to be a display problem when the description is not long enough @AnthonyBuisset Screenshot 2023-02-27 at 18 57 36

This happens only when no repo, we should never be the case as the project won't be visible. But fixed anyway 👍

**Comment by AnthonyBuisset** [comment]
> There seems to be a case when the contributor name display does not work ("github.com/undefined") @AnthonyBuisset Screenshot 2023-02-27 at 19 00 25

This should never happen as well but fixed anyway 👍

**Review by oscarwroche — APPROVED** [review]

**Pull request merged**
